<?php
/**
 * SuscripcionesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  mx\wire4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace mx\wire4;

use mx\wire4\Configuration;
use mx\wire4\ApiException;
use mx\wire4\ObjectSerializer;

/**
 * SuscripcionesApiTest Class Doc Comment
 *
 * @category Class
 * @package  mx\wire4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SuscripcionesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changeSubscriptionStatusUsingPUT
     *
     * Cambia el estatus de la suscripción.
     *
     */
    public function testChangeSubscriptionStatusUsingPUT()
    {
    }

    /**
     * Test case for preEnrollmentMonexUserUsingPOST
     *
     * Registra una pre-suscripción.
     *
     */
    public function testPreEnrollmentMonexUserUsingPOST()
    {
    }

    /**
     * Test case for removeEnrollmentUserUsingDELETE
     *
     * Elimina una suscripción por el identificador de la suscripción.
     *
     */
    public function testRemoveEnrollmentUserUsingDELETE()
    {
    }

    /**
     * Test case for removeSubscriptionPendingStatusUsingDELETE
     *
     * Elimina una pre-suscripción.
     *
     */
    public function testRemoveSubscriptionPendingStatusUsingDELETE()
    {
    }
}
