<?php
/**
 * AccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  mx\wire4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wire4RestAPI
 *
 * Referencia de API. La API de Wire4 está organizada en torno a REST
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace mx\wire4;

/**
 * AccountTest Class Doc Comment
 *
 * @category    Class
 * @description Objeto que contiene información de la cuenta
 * @package     mx\wire4
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Account"
     */
    public function testAccount()
    {
    }

    /**
     * Test attribute "amount_limit"
     */
    public function testPropertyAmountLimit()
    {
    }

    /**
     * Test attribute "bank_key"
     */
    public function testPropertyBankKey()
    {
    }

    /**
     * Test attribute "beneficiary_account"
     */
    public function testPropertyBeneficiaryAccount()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "institution"
     */
    public function testPropertyInstitution()
    {
    }

    /**
     * Test attribute "kind_of_relationship"
     */
    public function testPropertyKindOfRelationship()
    {
    }

    /**
     * Test attribute "numeric_reference_spei"
     */
    public function testPropertyNumericReferenceSpei()
    {
    }

    /**
     * Test attribute "payment_concept_spei"
     */
    public function testPropertyPaymentConceptSpei()
    {
    }

    /**
     * Test attribute "person"
     */
    public function testPropertyPerson()
    {
    }

    /**
     * Test attribute "relationship"
     */
    public function testPropertyRelationship()
    {
    }

    /**
     * Test attribute "rfc"
     */
    public function testPropertyRfc()
    {
    }
}
