<?php
/**
 * AccountRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  mx\wire4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace mx\wire4;

/**
 * AccountRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Objeto request para guardar la cuenta del beneficiario
 * @package     mx\wire4
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountRequest"
     */
    public function testAccountRequest()
    {
    }

    /**
     * Test attribute "accounts"
     */
    public function testPropertyAccounts()
    {
    }

    /**
     * Test attribute "cancel_return_url"
     */
    public function testPropertyCancelReturnUrl()
    {
    }

    /**
     * Test attribute "return_url"
     */
    public function testPropertyReturnUrl()
    {
    }
}
