<?php
/**
 * CodiOperationsFiltersRequestDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  mx\wire4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace mx\wire4;

/**
 * CodiOperationsFiltersRequestDTOTest Class Doc Comment
 *
 * @category    Class
 * @description CodiOperationsFiltersRequestDTO
 * @package     mx\wire4
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CodiOperationsFiltersRequestDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CodiOperationsFiltersRequestDTO"
     */
    public function testCodiOperationsFiltersRequestDTO()
    {
    }

    /**
     * Test attribute "amount_from"
     */
    public function testPropertyAmountFrom()
    {
    }

    /**
     * Test attribute "amount_to"
     */
    public function testPropertyAmountTo()
    {
    }

    /**
     * Test attribute "operation_date_from"
     */
    public function testPropertyOperationDateFrom()
    {
    }

    /**
     * Test attribute "operation_date_to"
     */
    public function testPropertyOperationDateTo()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "request_date_from"
     */
    public function testPropertyRequestDateFrom()
    {
    }

    /**
     * Test attribute "request_date_to"
     */
    public function testPropertyRequestDateTo()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
