<?php
/**
 * MessageSubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  mx\wire4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace mx\wire4;

use PHPUnit\Framework\TestCase;

/**
 * MessageSubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description Es el objeto del mensaje que se envía mediante webhook con la información de la suscripción a esta a esta API
 * @package     mx\wire4
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageSubscriptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MessageSubscription"
     */
    public function testMessageSubscription()
    {
    }

    /**
     * Test attribute "contract"
     */
    public function testPropertyContract()
    {
    }

    /**
     * Test attribute "masked_contract"
     */
    public function testPropertyMaskedContract()
    {
    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "user_key"
     */
    public function testPropertyUserKey()
    {
    }

    /**
     * Test attribute "user_secret"
     */
    public function testPropertyUserSecret()
    {
    }
}
