<?php
/**
 * MessageDepositReceivedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  mx\wire4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace mx\wire4;

/**
 * MessageDepositReceivedTest Class Doc Comment
 *
 * @category    Class
 * @description Es el objeto del mensaje que se envía mediante webhook con la información de una transferencia de entrada recibida.
 * @package     mx\wire4
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageDepositReceivedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MessageDepositReceived"
     */
    public function testMessageDepositReceived()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "beneficiary_account"
     */
    public function testPropertyBeneficiaryAccount()
    {
    }

    /**
     * Test attribute "beneficiary_name"
     */
    public function testPropertyBeneficiaryName()
    {
    }

    /**
     * Test attribute "beneficiary_rfc"
     */
    public function testPropertyBeneficiaryRfc()
    {
    }

    /**
     * Test attribute "cep"
     */
    public function testPropertyCep()
    {
    }

    /**
     * Test attribute "clave_rastreo"
     */
    public function testPropertyClaveRastreo()
    {
    }

    /**
     * Test attribute "confirm_date"
     */
    public function testPropertyConfirmDate()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "deposit_date"
     */
    public function testPropertyDepositDate()
    {
    }

    /**
     * Test attribute "depositant"
     */
    public function testPropertyDepositant()
    {
    }

    /**
     * Test attribute "depositant_alias"
     */
    public function testPropertyDepositantAlias()
    {
    }

    /**
     * Test attribute "depositant_clabe"
     */
    public function testPropertyDepositantClabe()
    {
    }

    /**
     * Test attribute "depositant_email"
     */
    public function testPropertyDepositantEmail()
    {
    }

    /**
     * Test attribute "depositant_rfc"
     */
    public function testPropertyDepositantRfc()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "monex_description"
     */
    public function testPropertyMonexDescription()
    {
    }

    /**
     * Test attribute "monex_transaction_id"
     */
    public function testPropertyMonexTransactionId()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "sender_account"
     */
    public function testPropertySenderAccount()
    {
    }

    /**
     * Test attribute "sender_bank"
     */
    public function testPropertySenderBank()
    {
    }

    /**
     * Test attribute "sender_name"
     */
    public function testPropertySenderName()
    {
    }

    /**
     * Test attribute "sender_rfc"
     */
    public function testPropertySenderRfc()
    {
    }
}
